YCSGAME/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import mainapp.views
from friendapp.views import send_friend_request, accept_friend_request

urlpatterns = [
    path('main/',include('mainapp.urls')),
    path('admin/', admin.site.urls),
    path('account/',include('accountapp.urls')),
    path('profile/',include('profileapp.urls')),
    path('friend/',include('friendapp.urls')),
    path('send_friend_request/<int:user_id>/', send_friend_request, name='send friend request'),
    path('accept_friend_request/<int:request_id>/', accept_friend_request, name='accept friend request'),
] +static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.generic import CreateView

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns =[
    path('create/',AccountCreateView.as_view(),name='create'),
    path('login/',LoginView.as_view(template_name='accountapp/login.html'),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('detail/<int:pk>',AccountDetailView.as_view(),name='detail'),
    path('update/<int:pk>',AccountUpdateView.as_view(),name='update'),
    path('delete/<int:pk>',AccountDeleteView.as_view(),name='delete'),
]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'
urlpatterns = [
    path('create/',ProfileCreateView.as_view(),name='create'),
    path('updata/<int:pk>',ProfileUpdateView.as_view(),name='update'),
]

accountapp/models.py
from django.db import models


# Create your models here.

class HelloWorld(models.Model):
    text = models.CharField(max_length=100, null=False)

accountapp/forms.py
#폼 형식을 변경하기 위해
from django.contrib.auth.forms import UserCreationForm


class AccountCreationForm(UserCreationForm): #usercreation form 상속
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs) #부모 에 초기화 접근하기 위해 super 사용

        self.fields['username'].disabled = True  #사용자 id 칸을 False 로 변경
        '''
        update 에서 id 를 못쓰게 만드는 새로운 폼을 만들었다.
        '''

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from accountapp.forms import AccountCreationForm
from accountapp.decorators import account_ownership_required


class AccountCreateView(CreateView):
    model = User  # 모델 지정  = User(장고에서 지정 해주는 모델 계정에 관한 정보가 들어있음)
    form_class = UserCreationForm  # 장고에서 제공하는 사용자 계정 form
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/create.html'


class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'


has_ownership = [login_required, account_ownership_required]


@method_decorator(has_ownership, 'get')  # 메소드에서 데코레이터를 적용한다 (적용할 데토레이터를 가져와야 한다,어떤 방식의 메소드 를 접근 할지)
@method_decorator(has_ownership, 'post')  # 애초에 클래스 메소드에서 데코레이터를 작동할수 있는 시스템을 만들어야 한다.
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountCreationForm
    template_name = 'accountapp/update.html'

    success_url = reverse_lazy('mainapp:mainpage')
    # def get_success_url(self):
    # return reverse('accountapp:detail', kwargs={'pk': self.object.pk})


@method_decorator(has_ownership, 'get')  # 메소드에서 데코레이터를 적용한다 (적용할 데토레이터를 가져와야 한다,어떤 방식의 메소드 를 접근 할지)
@method_decorator(has_ownership, 'post')  # 애초에 클래스 메소드에서 데코레이터를 작동할수 있는 시스템을 만들어야 한다.
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('mainapp:mainpage')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
     <div class = "text-center mw-500 m-auto">
        <form action="{% url 'accountapp:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form%}
                <div class = "m-5">
                    <input type = "submit" class="btn btn-dark rounded-pill px-5">
                </div>
        </form>
    </div>
{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
        <div class = "text-center mw-500 m-auto">  <!--bootstrap 에서 제공해주는 class-->
        <div class = "m-5"> <!--margin 5-->
            <h4>계정을 탈퇴 하시겠습니까?</h4>
        </div>
        <div class>
            <form action = "{% url 'accountapp:delete' pk=target_user.pk %}" method = "post"> {# 타겟 유저는 객체의 고유값 #}
                {% csrf_token %}
                <div class = "m-5">
                    <input type = "submit" class="btn btn-danger rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}  <!--extends 를 이용하여 basecopy.html 에 저장할 html 문서 -->
{% block content %}
    <div class = "text-center mw-500 m-auto">  <!--bootstrap 에서 제공해주는 class-->
        <div class = "m-5"> <!--margin 5-->
            {% if target_user.profile %} {# 프로필 만들었는지 확인 #}
                <img src = "{{ target_user.profile.image.url }}" class="profile_image m-4" alt = "profile image"> {# alt 는 이미지 가 안뜨면 보이는 text 를 보인다 #}
            <h2 class = "NNS_B">
                {{ target_user.profile.nickname }}
                {% if target_user == user %} {# user 랑 target 유저가 같은지 확인 #}
                <a href ="{% url 'profileapp:update' pk=target_user.profile.pk %}"
                class = "material-icons round_button"> {# target_user = accountsapp 에 target_user 고 거기서 profile 은 model 에 related_name 연결 이름 거기에 .pk 를 가져와라  #}
                  edit
                </a>
                {% endif %}
            </h2> {# views 에서 선언한 타킷 유저로 접근 한다 #}
            <h5>
                {{ target_user.profile.message }}
            </h5>
            {% else %}
            <h4>
                <a href="{% url 'profileapp:create' %}">
                Create Profile
            </a>
            </h4>
            {% endif %}
        </div>

        {% if user == target_user%} {# 유저와 == target 유저 가 같은지 확인 비회원인 상태에서 정보 변경 불가를 위해 무방비하게 링크 오픈ㅈ#}
        <div>
            <a href = "{% url 'accountapp:update' pk=target_user.pk %}" class="material-icons round_button mx-1"> {#detail 정보 보기 에서  -> 정보 수정 링크를 만들어주는게 자연스러움#}
                settings
            </a>
            <a href = "{% url 'accountapp:delete' pk=target_user.pk %}" class="material-icons round_button mx-1">
                close
            </a>
        </div>
    {% endif %}
    </div>
{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Login</h4>
        </div>
        <div>
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class = "m-5">
                    <input type = "submit" class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
     <div class = "text-center mw-500 m-auto">
        <form action="{% url 'accountapp:update' pk=user.pk %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form%}
                <div class = "m-5">
                    <input type = "submit" class="btn btn-dark rounded-pill px-5">
                </div>
        </form>
    </div>
{% endblock %}