YCSGAME/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import mainapp.views
from friendapp.views import send_friend_request, accept_friend_request

urlpatterns = [
    path('main/',include('mainapp.urls')),
    path('admin/', admin.site.urls),
    path('account/',include('accountapp.urls')),
    path('profile/',include('profileapp.urls')),
    path('friend/',include('friendapp.urls')),
    path('send_friend_request/<int:user_id>/', send_friend_request, name='send friend request'),
    path('accept_friend_request/<int:request_id>/', accept_friend_request, name='accept friend request'),
] +static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.generic import CreateView

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns =[
    path('create/',AccountCreateView.as_view(),name='create'),
    path('login/',LoginView.as_view(template_name='accountapp/login.html'),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('detail/<int:pk>',AccountDetailView.as_view(),name='detail'),
    path('update/<int:pk>',AccountUpdateView.as_view(),name='update'),
    path('delete/<int:pk>',AccountDeleteView.as_view(),name='delete'),
]

friendapp/urls.py
from django.urls import path

from friendapp import views
from friendapp.views import FriendSearchView, FriendListView, send_friend_request, accept_friend_request

app_name = 'friendapp'
urlpatterns = [
    path('search/?search=<str:username>',FriendSearchView.as_view(),name='search'),
    path('list/<int:pk>',FriendListView.as_view(),name='list'),
]

mainapp/urls.py
from django.urls import path

from mainapp.views import mainpage

app_name = 'mainapp'

urlpatterns =[
    path('main/',mainpage,name='mainpage')
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% include 'head.html' %}
<body>
    {% include 'header.html' %}
    <hr>
    {% include 'sidebar.html' %}
    {% block content %}
    {% endblock %}
    <hr>
    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
    <div style = "text-align: center">
        <div class='Ycs_footer_button'>
            <span>공지사항</span>
            <span>제휴문의</span>
            <span>서비스 소개</span>
        </div>
        <div class='Ycs_footer_logo'>
            <h5>YCS</h5>
        </div>
    </div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <title>YCS GAME</title>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Festive&family=Pacifico&family=Yuji+Hentaigana+Akari&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-square.css" rel="stylesheet">


    <link rel="stylesheet" type ="text/css" href="{% static 'base.css' %}">

    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">
    <style>

    </style>
    <style>

    </style>
</head>

templates/header.html
<div style="text-align: center">
    <div class="Ycs_head_logo">
        <h1>
            <a href="{% url 'mainapp:mainpage' %}">
            YCS GAME
            </a>
        </h1>
    </div>
</div>

templates/sidebar.html
<div class="sidenav">
    <div style="text-align: left">
            <div class="Ycs_Member_logo">
                <h2>YCS MEMBER</h2>
            </div>
            <div class="Ycs_Member_button">
                {% if not user.is_authenticated %}
                <span class="mx-2">
                    <a href="{% url 'accountapp:login' %}">
                        Login
                    </a>
                <br>
                <span class="mx-2">
                    <a href="{% url 'accountapp:create' %}">
                        Create Account
                    </a>
                </span>
                </span>
                {% else %}
                    <span class="mx-2">
                        <a href = "{% url 'accountapp:logout' %}">
                            Logout
                        </a>
                    </span>
                    <br>
                    <span class="mx-2">
                        <a href="{% url 'accountapp:detail' pk=user.pk %}">
                            Account
                        </a>
                    </span>
                    <br>
                    <span class="mx-2">
                        <a href="{% url 'friendapp:search' username=user.username%}">
                            Search Friend
                        </a>
                    </span>
                    <br>
                    <span class="mx-2">
                        <a href="{% url 'friendapp:list' pk=user.pk %}">
                            Friends list
                        </a>
                    </span>

                {% endif %}
                <br>
            </div>

            <div class="Ycs_Game_logo">
                <h2>YCS Game</h2>
            </div>
            <div class="Ycs_Game_button">
                <span class="mx-2">
                    <a>
                        Room Making
                    </a>
                </span>
            </div>
    </div>
</div>